# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

HISTCONTROL=ignoreboth
shopt -s histappend
HISTSIZE=5000000
HISTFILESIZE=5000000

shopt -s checkwinsize
shopt -s globstar

PS1='\[\033[01;32m\]\h\[\033[00m\] \[\033[01;34m\]\w\[\033[00m\] \$ '

[ -f $HOME/.bash_secrets ] && . "$HOME/.bash_secrets"
[ -f $HOME/.bash_local ] && . "$HOME/.bash_local"

if [ -z "$PROJECTS_HOME" ]
then
    export PROJECTS_HOME="$HOME/repo"
fi

function prj() {
    RESULT=$(find "$PROJECTS_HOME/" -maxdepth 3 -name '.git' -type d -printf '%h\n' | sed "s#$PROJECTS_HOME/##g" | fzf)
    cd "$PROJECTS_HOME/$RESULT"
}

function vrg() {
    nvim -c ":Rg $1"
}

alias nf='nvim $(fzf)'
alias forgetful_ssh='ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
alias forgetful_scp='scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
export GH_HOST=github.adtran.com

# BEGIN ANSIBLE MANAGED BLOCK ta5k
export GHS_LMWHICH="@ghs"
export GHS_LMHOST="@corp-licmgr.adtran.com"
# END ANSIBLE MANAGED BLOCK ta5k
export ARTIFACTORY_SERVER=https://artifactory.adtran.com
export DOCKERBINARY=/opt/lsk-docker/docker

if command -v porg >/dev/null
then
eval "$(porg _completions bootstrap bash)"
fi

export P4CONFIG=.p4config
export P4IGNORE=.p4ignore
export PACKAGE_MAKE_USE_BEAR=1
export OS_CLOUD=openstack

export VISUAL="nvim"
export EDITOR="nvim"

export FZF_DEFAULT_COMMAND="fd --type f -I --ignore-file $HOME/.config/fdignore"
